doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
            AptoPropertyUuid:
                class: 'Apto\Base\Infrastructure\AptoBaseBundle\Doctrine\Dbal\Types\AptoPropertyUuid'
            AptoPropertyCreated:
                class: 'Apto\Base\Infrastructure\AptoBaseBundle\Doctrine\Dbal\Types\AptoPropertyCreated'
            AptoPropertyTranslatedValue:
                class: 'Apto\Base\Infrastructure\AptoBaseBundle\Doctrine\Dbal\Types\AptoPropertyTranslatedValue'
            AptoPropertyJsonSerializable:
                class: 'Apto\Base\Infrastructure\AptoBaseBundle\Doctrine\Dbal\Types\AptoPropertyJsonSerializable'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        dql:
            string_functions:
                MATCH: 'Apto\Base\Infrastructure\AptoBaseBundle\Doctrine\Orm\Query\MatchAgainst'
                JSON_EXTRACT: 'Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract'
                JSON_SEARCH: 'Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch'
                JSON_CONTAINS: 'Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
