framework:
    messenger:
        default_bus: message_bus
        buses:
            message_bus:
            query_bus:
            event_bus:
                default_middleware: allow_no_handlers
            command_bus:
                middleware:
                    - doctrine_transaction