framework:
    default_locale: de_DE
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - de_DE
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
