volumes:
    apto-mariadb-volume:
networks:
    apto-docker-network:
        name: apto-docker-network-${APTO_DOCKER_HOST}-${APTO_DOCKER_PORT}

services:
    apto-node-service:
        image: node:lts-alpine
        container_name: apto-node-container-${APTO_DOCKER_HOST}-${APTO_DOCKER_PORT}
        user: node
        working_dir: /home/node
        volumes:
            - .:/home/node
        networks:
            - apto-docker-network
        depends_on:
            - apto-apache-service
    apto-apache-service:
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker/apache/Dockerfile
        container_name: apto-apache-container-${APTO_DOCKER_HOST}-${APTO_DOCKER_PORT}
        ports:
            - "${APTO_DOCKER_PORT}:80"
        volumes:
            - .:/var/www/html
        networks:
            - apto-docker-network
        depends_on:
            - apto-mariadb-service
    apto-mariadb-service:
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker/mariadb/Dockerfile
            args:
                APTO_DOCKER_DOMAIN: ${APTO_DOCKER_DOMAIN}
        container_name: apto-mariadb-container-${APTO_DOCKER_HOST}-${APTO_DOCKER_PORT}
        environment:
            - MARIADB_ROOT_PASSWORD=${APTO_DOCKER_MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${APTO_DOCKER_MARIADB_DATABASE}
            - MARIADB_USER=${APTO_DOCKER_MARIADB_USER}
            - MARIADB_PASSWORD=${APTO_DOCKER_MARIADB_PASSWORD}
        volumes:
            - apto-mariadb-volume:/var/lib/mysql
        networks:
            - apto-docker-network
        ports:
            - ${APTO_DOCKER_MARIADB_PORT}:3306
    apto-pma-service:
        networks:
            - apto-docker-network
        restart: always
        container_name: apto-pma-container-${APTO_DOCKER_HOST}-${APTO_DOCKER_PORT}
        hostname: localhost
        image: phpmyadmin/phpmyadmin:5.2
        links:
            - apto-mariadb-service
        ports:
            - ${APTO_DOCKER_PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: apto-mariadb-service
            PMA_PORT: 3306
            UPLOAD_LIMIT: 1028M
