<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Apto\Base\Infrastructure\AptoBaseBundle\AptoBaseBundle::class => ['all' => true],
    Apto\Catalog\Infrastructure\AptoCatalogBundle\AptoCatalogBundle::class => ['all' => true],
    Apto\Plugins\AreaElement\Infrastructure\AreaElementBundle\AreaElementBundle::class => ['all' => true],
    Apto\Plugins\CustomText\Infrastructure\CustomTextBundle\CustomTextBundle::class => ['all' => true],
    Apto\Plugins\FileUpload\Infrastructure\FileUploadBundle\FileUploadBundle::class => ['all' => true],
    Apto\Plugins\FloatInputElement\Infrastructure\FloatInputElementBundle\FloatInputElementBundle::class => ['all' => true],
    Apto\Plugins\MaterialPickerElement\Infrastructure\MaterialPickerElementBundle\MaterialPickerElementBundle::class => ['all' => true],
    Apto\Plugins\PricePerUnitElement\Infrastructure\PricePerUnitElementBundle\PricePerUnitElementBundle::class => ['all' => true],
    Apto\Plugins\SelectBoxElement\Infrastructure\SelectBoxElementBundle\SelectBoxElementBundle::class => ['all' => true],
    Apto\Plugins\WidthHeightElement\Infrastructure\WidthHeightElementBundle\WidthHeightElementBundle::class => ['all' => true],
    Apto\Plugins\DateElement\Infrastructure\DateElementBundle\DateElementBundle::class => ['all' => true],
    Apto\Plugins\HintElement\Infrastructure\HintElementBundle\HintElementBundle::class => ['all' => true],
    Apto\Plugins\RequestForm\Infrastructure\RequestFormBundle\RequestFormBundle::class => ['all' => true],
    Apto\Plugins\ImageUpload\Infrastructure\ImageUploadBundle\ImageUploadBundle::class => ['all' => true],
    Apto\Plugins\PartsList\Infrastructure\AptoPartsListBundle\AptoPartsListBundle::class => ['all' => true],
    Apto\Plugins\FrontendUsers\Infrastructure\FrontendUsersBundle\FrontendUsersBundle::class => ['all' => true],
    Apto\Plugins\ImportExport\Infrastructure\ImportExportBundle\ImportExportBundle::class => ['all' => true],
];
