# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    apto_installer: '%env(APTO_INSTALLER)%'
    client_environment: '%env(APTO_CLIENT_ENVIRONMENT)%'
    root_directory: '%env(APTO_ROOT_DIRECTORY)%'
    public_folder: '%env(APTO_PUBLIC_FOLDER)%'
    image_magick_path: '%env(APTO_IMAGE_MAGICK_PATH)%'
    graphics_magick_path: '%env(APTO_GRAPHICS_MAGICK_PATH)%'
    media_directory: '%kernel.project_dir%/web/public/media'
    media_relative_path: '%public_folder%/public/media'
    thumb_route_path: '/public/thumbs'
    thumb_directory: '%kernel.project_dir%/web/public/thumbs'
    thumb_relative_path: '%public_folder%/public/thumbs'
    cache_directory: '%kernel.project_dir%/web/public/cache'
    cache_relative_path: '%public_folder%/public/cache'
    assets_directory: '%kernel.project_dir%/web/public/assets'
    assets_relative_path: '%public_folder%/public/assets'

imports:
    - { resource: parameters.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Apto\:
        resource: '../src/Apto/'
        exclude:
            - '../src/Apto/DependencyInjection/'
            - '../src/Apto/*/*/*/DependencyInjection/'
            - '../src/Apto/Plugins/*/*/*/DependencyInjection/'
            - '../src/Apto/Kernel.php'
            - '../src/Apto/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
